### PR TITLE
Wechaty v1.x API

### PR DESCRIPTION
**Pull request by huan**
@padlocal I have upgraded the code base with the ES Module & Wechaty v1.x, please review and let me know what you think.

Thank you very much!

Related to:

- https://github.com/wechaty/puppet/issues/164
- https://github.com/Chatie/tsconfig/issues/16

### CODE REVIEW

**Comment by huan** [comment]
Have removed the ESM from this PR with the latest commits.

I hope we can upgrade to Wechaty v1 soon!

**Comment by leochen-g** [comment]
我把esm分支拉到本地跑了一下，发现安装依赖并没有问题，action 跑的时候可能是超时导致的失败。不过安装完依赖在运行`npm run test `的时候，出现了一下报错，似乎是`wechaty-puppet/types`的引用存在问题，按照正常情况应该引用的是esm里的types，但是在运行test的时候查找的是cjs中的types

* node环境：16.13.0
* Mac

```
nvm use v16
Now using node v16.13.0 (npm v8.1.0)
➜  puppet-padlocal git:(esm) npm i
npm WARN deprecated @types/quick-lru@3.0.0: This is a stub types definition. quick-lru provides its own type definitions, so you do not need this installed.
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated axios@0.15.3: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'

added 1175 packages, and audited 1337 packages in 2m

7 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (8 moderate, 5 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
➜  puppet-padlocal git:(esm) npm run test

> wechaty-puppet-padlocal@1.11.6 test
> npm-run-all lint test:unit


> wechaty-puppet-padlocal@1.11.6 lint
> npm-run-all lint:es lint:ts lint:md


> wechaty-puppet-padlocal@1.11.6 lint:es
> eslint "src/**/*.ts" "tests/**/*.test.ts" --ignore-pattern tests/fixtures/

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.5

Please only submit bug reports when using the officially supported version.

=============

> wechaty-puppet-padlocal@1.11.6 lint:ts
> tsc --isolatedModules --noEmit


> wechaty-puppet-padlocal@1.11.6 lint:md
> markdownlint README.md


> wechaty-puppet-padlocal@1.11.6 test:unit
> jest

WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
 FAIL  tests/wechaty-api.test.ts
  ● Test suite failed to run

    **Cannot find module 'wechaty-puppet/types' from 'node_modules/wechaty/dist/cjs/src/mods/mod.js'**

    Require stack:
      node_modules/wechaty/dist/cjs/src/mods/mod.js
      tests/wechaty-api.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/wechaty/src/mods/mod.ts:39:1)

 FAIL  tests/wechaty-login.test.ts
  ● Test suite failed to run

    **Cannot find module 'wechaty-puppet/types' from 'node_modules/wechaty/dist/cjs/src/mods/mod.js'**

    Require stack:
      node_modules/wechaty/dist/cjs/src/mods/mod.js
      tests/wechaty-common.ts
      tests/wechaty-login.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/wechaty/src/mods/mod.ts:39:1)

 FAIL  tests/wechaty-push.test.ts
  ● Test suite failed to run

    **Cannot find module 'wechaty-puppet/types' from 'node_modules/wechaty/dist/cjs/src/mods/mod.js'**

    Require stack:
      node_modules/wechaty/dist/cjs/src/mods/mod.js
      tests/wechaty-push.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/wechaty/src/mods/mod.ts:39:1)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From tests/wechaty-api.test.ts.

      at node_modules/gifwrap/src/gifcodec.js:7:15

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From tests/wechaty-push.test.ts.

      at node_modules/gifwrap/src/gifcodec.js:7:15

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From tests/wechaty-login.test.ts.

      at node_modules/gifwrap/src/gifcodec.js:7:15
Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        5.557 s
Ran all test suites.
ERROR: "test:unit" exited with 1.

```

**Comment by huan** [comment]
Hi @leochen-g 

Thank you very much for taking look at this PR!

The error messages you have posted is very wired because we can require wechaty without any problem with CLI:

```sh
$ node
Welcome to Node.js v16.13.2.
Type ".help" for more information.
> require('wechaty-puppet/types')
{
  ContactGender: [Getter],
  Contact: [Getter],
  FriendshipScene: [Getter],
  Friendship: [Getter],
  Image: [Getter],
  Message: [Getter],
  Post: [Getter],
  Tap: [Getter],
  Sayable: [Getter],
  Payload: [Getter],
  Dirty: [Getter],
  ScanStatus: [Getter],
  YOU: [Getter],
  CHAT_EVENT_DICT: [Getter],
  PUPPET_EVENT_DICT: [Getter]
}
```

So I added another minimum unit test that loads the `wechaty` and found that it can work without any problem, with `tap` runner:

```sh
$ ./tests/wechaty-login.spec.ts 
TAP version 13
# Subtest: smoke testing
    ok 1 - bot has created
    1..1
ok 1 - smoke testing # time=6.318ms

1..1
# time=17.664ms
```

So I guess the problem might relate to the `jest` test runner?

Not sure about it but hope the above information could be helpful for the future investigating.

**Comment by leochen-g** [comment]
@huan 有点不太明白哈，就是现在1.x版本使用的应该是esm的导入方式引入包，但是我看报错，引入的wechaty是cjs的，这个是不是不太对，packages.json 里我看并没有`type: 'module'` ,其他puppet里我看是有这个配置的，会和这个有关系吗

**Comment by huan** [comment]
> 现在1.x版本使用的应该是esm的导入方式引入包

This is partially correct.

The 1.x version of Wechaty is built with a Dual-ESM-CJS pattern, which means that when it is loaded by an ESM module then it will be an ESM module, otherwise when it is loaded by a CJS module then it will be a CJS module.

When the Wechaty is loading with the correct version of the wechaty-puppet-padlocal (which is a CJS module), then it will act as a CJS module and be loaded as CJS.

> 但是我看报错，引入的wechaty是cjs的，这个是不是不太对

According to my above explanation: when the CJS wechaty-puppet-padlocal load the wechaty, the wechaty will be in CJS mode.

> packages.json 里我看并没有type: 'module'

If the package.json specifies a `type: 'module'`, then it means that the current module is ESM.

wechaty-puppet-padlocal has no `type: 'module'` so it's a CJS

> 其他puppet里我看是有这个配置的

wechaty, wechaty-puppet, and other Wechaty ecosystem modules have `'type: 'module'` by default, which means that they are ESM modules.

And we have enabled the Dual-ESM-CJS for them when they have been built, so they can be used either by ESM or CJS.

I hope my explanations help you understand the situation, please feel free to let me know if you have more questions.

**Comment by leochen-g** [comment]
> 
好的 谢谢解惑 我再研究一下

**Comment by huan** [comment]
@leochen-g You are welcome!

**Comment by whyour** [comment]
any progress?

**Review by padlocal — APPROVED** [review]

**Comment by huan** [comment]
Finally! Congratulations! 🎉

**Pull request merged**
